services:
  db:
    image: mariadb@sha256:0a620383fe05d20b3cc7510ebccc6749f83f1b0f97f3030d10dd2fa199371f07
    environment:
    - MARIADB_RANDOM_ROOT_PASSWORD=1
    - MARIADB_DATABASE=ezxss
    - MARIADB_USER=ezxss
    - MARIADB_PASSWORD=ezxss
  ezxss:
    # image: ghcr.io/gadgetmg/ezxss:master
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    environment:
    - EZXSS_DBHOST=db
    - EZXSS_DBUSER=ezxss
    - EZXSS_DBPASSWORD=ezxss
